<?php

namespace Database\Seeders\SpecializedEducationalSupport;

use Illuminate\Database\Seeder;
use App\Models\Permission;
use App\Models\SpecializedEducationalSupport\Position;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions = [
            [
                'name' => 'Professor AEE',
                'description' => 'Responsável pelo Atendimento Educacional Especializado e elaboração de planos de intervenção pedagógica.',
                'permissions' => [
                    'deficiency.view',
                    'semester.view',
                    'course.view',
                    'discipline.view',
                    'student.view',
                    'guardian.view',
                    'professional.view',
                    'teacher.view',
                    'student-context.view',
                    'student-context.create',
                    'student-context.update',
                    'student-deficiency.view',
                    'student-deficiency.create',
                    'student-deficiency.update',
                    'session.view',
                    'session.view-all',
                    'session.view-own',
                    'session.create',
                    'session.update',
                    'session.delete',
                    'session-record.view',
                    'session-record.view-all',
                    'session-record.view-own',
                    'session-record.create',
                    'session-record.update',
                    'session-record.delete',
                    'student-course.view',
                    'pendency.view',
                    'pendency.create',
                    'pendency.update',
                    'pei.view',
                    'pei.create',
                    'pei.update',
                    'pei.delete',
                    'pei-discipline.view',
                    'pei-discipline.create',
                    'pei-discipline.update',
                    'pei-discipline.delete',
                    'student-document.view',
                    'student-document.create',
                    'student-document.update',
                    'student-document.delete',
                    'assistive-technology.index',
                    'assistive-technology.create',
                    'assistive-technology.store',
                    'assistive-technology.show',
                    'assistive-technology.edit',
                    'assistive-technology.update',
                    'assistive-technology.pdf',
                    'assistive-technology.logs',
                    'assistive-technology.inspection.show',
                    'material.index',
                    'material.create',
                    'material.store',
                    'material.show',
                    'material.edit',
                    'material.update',
                    'material.pdf',
                    'material.logs',
                    'material.inspection.show',
                    'barrier.index',
                    'barrier.create',
                    'barrier.store',
                    'barrier.show',
                    'barrier.edit',
                    'barrier.update',
                    'barrier.pdf',
                    'barrier.inspection.show',
                    'loan.index',
                    'loan.create',
                    'loan.store',
                    'loan.show',
                    'loan.edit',
                    'loan.update',
                    'loan.return',
                    'loan.pdf',
                    'institutional-event.index',
                    'institutional-event.create',
                    'institutional-event.store',
                    'institutional-event.show',
                    'institutional-event.edit',
                    'institutional-event.update',
                    'institutional-event.pdf',
                    'waitlist.index',
                    'waitlist.create',
                    'waitlist.store',
                    'waitlist.show',
                    'waitlist.edit',
                    'waitlist.update',
                    'waitlist.cancel',
                    'waitlist.pdf',
                    'barrier-category.index',
                    'barrier-category.show',
                    'institution.index',
                    'institution.show',
                    'location.index',
                    'location.show',
                    'accessibility-feature.index',
                    'accessibility-feature.show',
                ],
            ],
            [
                'name' => 'Coordenador do NAPNE',
                'description' => 'Profissional responsável pela gestão das ações do núcleo, articulação institucional e acompanhamento dos atendimentos.',
                'permissions' => ['*'],
            ],
            [
                'name' => 'Secretário',
                'description' => 'Responsável pelo apoio administrativo, organização de documentos, atendimento ao público e suporte às atividades do NAPNE.',
                'permissions' => [
                    'people.view',
                    'people.create',
                    'people.update',
                    'deficiency.view',
                    'position.view',
                    'semester.view',
                    'course.view',
                    'discipline.view',
                    'student.view',
                    'student.create',
                    'student.update',
                    'guardian.view',
                    'guardian.create',
                    'guardian.update',
                    'professional.view',
                    'teacher.view',
                    'student-context.view',
                    'student-deficiency.view',
                    'session.view',
                    'session.view-all',
                    'session.create',
                    'session.update',
                    'student-course.view',
                    'student-course.create',
                    'student-course.update',
                    'pendency.view',
                    'pendency.create',
                    'pendency.update',
                    'student-document.view',
                    'student-document.create',
                    'student-document.update',
                    'assistive-technology.index',
                    'assistive-technology.create',
                    'assistive-technology.store',
                    'assistive-technology.show',
                    'assistive-technology.edit',
                    'assistive-technology.update',
                    'assistive-technology.pdf',
                    'assistive-technology.logs',
                    'material.index',
                    'material.create',
                    'material.store',
                    'material.show',
                    'material.edit',
                    'material.update',
                    'material.pdf',
                    'material.logs',
                    'barrier.index',
                    'barrier.create',
                    'barrier.store',
                    'barrier.show',
                    'barrier.edit',
                    'barrier.update',
                    'barrier.pdf',
                    'loan.index',
                    'loan.create',
                    'loan.store',
                    'loan.show',
                    'loan.edit',
                    'loan.update',
                    'loan.return',
                    'loan.pdf',
                    'institutional-event.index',
                    'institutional-event.create',
                    'institutional-event.store',
                    'institutional-event.show',
                    'institutional-event.edit',
                    'institutional-event.update',
                    'institutional-event.pdf',
                    'waitlist.index',
                    'waitlist.create',
                    'waitlist.store',
                    'waitlist.show',
                    'waitlist.edit',
                    'waitlist.update',
                    'waitlist.cancel',
                    'waitlist.pdf',
                    'barrier-category.index',
                    'barrier-category.show',
                    'institution.index',
                    'institution.create',
                    'institution.store',
                    'institution.show',
                    'institution.edit',
                    'institution.update',
                    'location.index',
                    'location.create',
                    'location.store',
                    'location.show',
                    'location.edit',
                    'location.update',
                    'accessibility-feature.index',
                    'accessibility-feature.create',
                    'accessibility-feature.store',
                    'accessibility-feature.show',
                    'accessibility-feature.edit',
                    'accessibility-feature.update',
                ],
            ],
            [
                'name' => 'Assessoria Pedagógica',
                'description' => 'Responsável pelo acompanhamento pedagógico, articulação com docentes e suporte à construção e revisão dos PEIs.',
                'permissions' => [
                    'deficiency.view',
                    'semester.view',
                    'course.view',
                    'discipline.view',
                    'student.view',
                    'guardian.view',
                    'professional.view',
                    'teacher.view',
                    'student-context.view',
                    'student-context.create',
                    'student-context.update',
                    'student-deficiency.view',
                    'student-deficiency.update',
                    'session.view',
                    'session.view-all',
                    'session-record.view',
                    'session-record.view-all',
                    'student-course.view',
                    'pendency.view',
                    'pendency.create',
                    'pendency.update',
                    'pei.view',
                    'pei.create',
                    'pei.update',
                    'pei-discipline.view',
                    'pei-discipline.create',
                    'pei-discipline.update',
                    'student-document.view',
                    'report.index',
                    'report.available',
                    'report.meta',
                    'report.run',
                    'report.pdf',
                    'assistive-technology.index',
                    'assistive-technology.create',
                    'assistive-technology.store',
                    'assistive-technology.show',
                    'assistive-technology.edit',
                    'assistive-technology.update',
                    'assistive-technology.pdf',
                    'assistive-technology.logs',
                    'assistive-technology.inspection.show',
                    'material.index',
                    'material.create',
                    'material.store',
                    'material.show',
                    'material.edit',
                    'material.update',
                    'material.pdf',
                    'material.logs',
                    'material.inspection.show',
                    'barrier.index',
                    'barrier.create',
                    'barrier.store',
                    'barrier.show',
                    'barrier.edit',
                    'barrier.update',
                    'barrier.pdf',
                    'barrier.inspection.show',
                    'loan.index',
                    'loan.create',
                    'loan.store',
                    'loan.show',
                    'loan.edit',
                    'loan.update',
                    'loan.return',
                    'loan.pdf',
                    'institutional-event.index',
                    'institutional-event.create',
                    'institutional-event.store',
                    'institutional-event.show',
                    'institutional-event.edit',
                    'institutional-event.update',
                    'institutional-event.pdf',
                    'waitlist.index',
                    'waitlist.create',
                    'waitlist.store',
                    'waitlist.show',
                    'waitlist.edit',
                    'waitlist.update',
                    'waitlist.cancel',
                    'waitlist.pdf',
                    'barrier-category.index',
                    'barrier-category.create',
                    'barrier-category.store',
                    'barrier-category.show',
                    'barrier-category.edit',
                    'barrier-category.update',
                    'institution.index',
                    'institution.create',
                    'institution.store',
                    'institution.show',
                    'institution.edit',
                    'institution.update',
                    'location.index',
                    'location.create',
                    'location.store',
                    'location.show',
                    'location.edit',
                    'location.update',
                    'accessibility-feature.index',
                    'accessibility-feature.create',
                    'accessibility-feature.store',
                    'accessibility-feature.show',
                    'accessibility-feature.edit',
                    'accessibility-feature.update',
                ],
            ],
        ];

        $permissionIdsBySlug = Permission::pluck('id', 'slug');
        $allPermissionIds = $permissionIdsBySlug->values()->all();

        foreach ($positions as $data) {
            $position = Position::updateOrCreate(
                ['name' => $data['name']],
                ['description' => $data['description'], 'is_active' => true]
            );

            $permissionSlugs = $data['permissions'] ?? [];
            $permissionIds = in_array('*', $permissionSlugs, true)
                ? $allPermissionIds
                : collect($permissionSlugs)
                    ->map(fn (string $slug) => $permissionIdsBySlug->get($slug))
                    ->filter()
                    ->values()
                    ->all();

            $position->permissions()->sync($permissionIds);
        }
    }
}
